### ISSUE TITLE
IPS is causing file permission errors with netCDF4 on Cori

### ISSUE THREAD

**Issue by cianciosa** [HPC-SimTools/IPS-framework#168]
I have a workflow that try to write a file to a directory outside of the component working directory. Attached is a example program that shows that I can write text files but I cannot write netCDF files using the netCDF4 module.

[debug.zip](https://github.com/HPC-SimTools/IPS-framework/files/9435004/debug.zip)

This producing an error 
```
cat log.warning
2022-08-26 10:05:44,744 driver__test_driver_1 ERROR    Uncaught Exception in component method.
Traceback (most recent call last):
  File "/global/homes/m/markcian/.conda/envs/test_env/lib/python3.10/site-packages/ipsframework/component.py", line 138, in __run__
    retval = method(*self.args, **keywords)
  File "/global/homes/m/markcian/.conda/envs/test_env/lib/python3.10/site-packages/test_component/test_component.py", line 15, in step
    with netCDF4.Dataset('/global/homes/m/markcian/debug/test/temp/test_comp.nc', 'w') as netcdf_ref:
  File "src/netCDF4/_netCDF4.pyx", line 2353, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1963, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'/global/homes/m/markcian/debug/test/temp/test_comp.nc'
```

This appears only on Cori. Running on my laptop doesn't show this problem.

**Comment by elwasif** [comment]
This appears to be a limitation at NERSC with their file systems. The attached code shows the same problem just using the system NetCDF4 
```python
import netCDF4
class test_driver():

    def step(self, timeStamp=0.0):
        with open('/global/homes/e/elwasif/test/test_comp.txt', 'w') as txt_ref:
            txt_ref.write('Hello')

        with netCDF4.Dataset('/global/homes/e/elwasif/test/test_comp.nc', 'w') as netcdf_ref:
        #with netCDF4.Dataset('/global/cscratch1/sd/elwasif/debug/test_component/test_comp.nc', 'w') as netcdf_ref:
            scalar = netcdf_ref.createDimension('s', 1)
            netcdf_ref.createVariable('v', 'f8', ('s'))

d = test_driver()
d.step()
```

```
elwasif@nid00882:/global/cscratch1/sd/elwasif/debug/test_component> module load python/3.9-anaconda-2021.11 
elwasif@nid00882:/global/cscratch1/sd/elwasif/debug/test_component> python3  test_component.py
Traceback (most recent call last):
  File "/global/cscratch1/sd/elwasif/debug/test_component/test_component.py", line 15, in <module>
    d.step()
  File "/global/cscratch1/sd/elwasif/debug/test_component/test_component.py", line 9, in step
    with netCDF4.Dataset('/global/homes/e/elwasif/test/test_comp.nc', 'w') as netcdf_ref:
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'/global/homes/e/elwasif/test/test_comp.nc'
```

I think you may want to email consult and ask about this behavior

**Comment by rosswhitfield** [comment]
I can reproduce the issue.

`PermissionError: [Errno 13]` seems to apply to any filesystem error, _e.g._ if the directory doesn't exist.

This seems to work on the Scratch filesystem but not home.

I don't think this is a problem with IPS itself but running with `srun`

Running the `test_bin.py` with `srun` in your home directory will fail:

```
srun -p debug -N 1 -t 00:30:00 -C haswell python test_bin.py
```

but if you disable HDF file locking it succeeds:

```
HDF5_USE_FILE_LOCKING=FALSE srun -p debug -N 1 -t 00:30:00 -C haswell python test_bin.py
```

**Comment by cianciosa** [comment]
I've opened a ticket with nersc with a new test case that doesn't use IPS. I've tried adding HDF5_USE_FILE_LOCKING=FALSE to the conda env but it failed to resolve the issue. Since this doesn't appear to be an IPS issue, I will close this.

[debug.tar.gz](https://github.com/HPC-SimTools/IPS-framework/files/9435553/debug.tar.gz)
